/// Flutter icons Stetoscop
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Stetoscop
///      fonts:
///       - asset: fonts/Stetoscop.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Stetoscop {
  Stetoscop._();

  static const _kFontFam = 'Stetoscop';
  static const String? _kFontPkg = null;

  static const IconData ic_m_measure =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class Input_icons {
  Input_icons._();

  static const _kFontFam = 'Input_icons';
  static const String? _kFontPkg = null;

  static const IconData input =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class Ic_donasi {
  Ic_donasi._();

  static const _kFontFam = 'Ic_donasi';
  static const String? _kFontPkg = null;

  static const IconData ic_donasi =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class Ic_obat {
  Ic_obat._();

  static const _kFontFam = 'Ic_obat';
  static const String? _kFontPkg = null;

  static const IconData ic_obat =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class Iconic {
  Iconic._();

  static const IconData ic_lapangan =
      IconData(0xe800, fontFamily: "Ic_lapangan", fontPackage: null);

  static const IconData ic_obat =
      IconData(0xe800, fontFamily: "Ic_obat", fontPackage: null);

  static const IconData ic_m_measure =
      IconData(0xe800, fontFamily: "Stetoscop", fontPackage: null);
}

class Ic_lapangan {
  Ic_lapangan._();

  static const _kFontFam = 'Ic_lapangan';
  static const String? _kFontPkg = null;

  static const IconData ic_lapangan =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData access_alarms =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class Ic_layer {
  Ic_layer._();

  static const _kFontFam = 'Ic_layer';
  static const String? _kFontPkg = null;

  static const IconData fi_layers =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class Ic_lapang {
  Ic_lapang._();

  static const _kFontFam = 'Ic_lapang';
  static const String? _kFontPkg = null;

  static const IconData ic_lapangans =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
