/// Flutter icons Ic_lapang
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Ic_lapang
///      fonts:
///       - asset: fonts/Ic_lapang.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Ic_lapang {
  Ic_lapang._();

  static const _kFontFam = 'Ic_lapang';
  static const String? _kFontPkg = null;

  static const IconData ic_lapangans = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
